### ISSUE TITLE
Solution is not compatible with RestSharp 107.0.1

### ISSUE THREAD

**Issue by rozeboosje** [docusign/docusign-esign-csharp-client#358] opened 2022-01-07 15:34 UTC
For compatibility reasons we have done a rebuild of this client targeting .NET Framework 4.8

We also like to keep our NuGet packages up to date

You're using a NuGet package for RestSharp by John Sheehan, Andrew Young, Alexey Zimarev and RestSharp community

They have released a build 107.0.1 which breaks completely with the 106 builds - for example all the Interfaces are gone and they have removed synchronous methods.

At the moment this package is only used by DocuSign and not by any other 3rd party components so this is not going to cause us any difficulties, but if we ever decide to start using another 3rd party component that uses RestSharp 107.0.1 we will be in trouble.

Would it be possible to modify your code to use RestSharp 107.0.1 or even remove dependencies to this component completely?

**Comment by grippstick** [comment] 2022-02-24 17:10
I attempted to upgrade to Docusign C# SDK 5.9 and everything just crashes, because of the RestSharp dependency.

I get "System.MissingMethodException: Method not found: 'Void RestSharp.RestClient.set_Proxy(System.Net.IWebProxy)'.", when I attempt to instantiate an APIClient.

`var apiClient = new ApiClient();`

**Comment by joshjeppson** [comment] 2022-03-16 18:59
We had similar issues after attempting an upgrade to RestSharp v107. Please remove the dependency or upgrade asap.

**Comment by warrenharding** [comment] 2022-03-16 19:10
Issues with RestSharp v1.7.0 Had to revert to v1.6.15. Please upgrade as soon as possible and let us know.

**Comment by rozeboosje** [comment] 2022-03-16 19:14
It's absurd to say the least that you should choose to use a third party product like "Restsharp" to do something as basic as calling Restful APIs. For Pete's sake, just remove this reference and call the APIs directly. I have done this for other REST APIs and it ain't Rocket Surgery

**Comment by rozeboosje** [comment] 2022-03-29 17:42
@dmartin00  is there anything happening on this? This has caused problems for over 2 months now.

**Comment by codsay** [comment] 2022-04-06 04:22
+1 - I'm having this exactly problem!

**Comment by rozeboosje** [comment] 2022-04-06 08:32
Hellooooooo.... Helloooooooo

*faint echo*

Anybody home?

**Comment by daothanhduy305** [comment] 2022-04-06 14:11
knock knock!
I'm crying out.

**Comment by jglassenberg** [comment] 2022-04-06 16:43
Sorry for the lack of updates here.  This is Jeremy from Docusign's SDK team.  

We synced internally on this matter and are evaluating the best fix (I can't share the plan just yet, but basically we were discussing updating RestSharp vs removing the dependency), based on feedback both here and in other messages directly to us regarding challenges with RestSharp (there have been a few).  

In the past few days we agreed that this will be the priority issue to resolve for our next SDK update.  Unfortunately, I don't yet have an ETA.  I know it will not be resolved this week or next, based on our initial assessment.  I'll share an update for everyone here next week on the status, however.

**Comment by rozeboosje** [comment] 2022-04-06 17:27
@jglassenberg Thank you! I'd be happy to wait now, knowing that it will be addressed.

**Comment by jglassenberg** [comment] 2022-04-14 04:50
I was hoping for a more clear update by mid-week, but unfortunately, our developers were caught up in another SDK issue much of this week.  We're still shooting for a better update by end of week.  Sorry for the continued holdup.

**Comment by jglassenberg** [comment] 2022-04-22 04:31
Update for this week - Engineering began working on the matter this week, but I don't expect a resolution this week or next.  We're still evaluating options and scope will depend on what we select.  But I'll continue to post an update here weekly at minimum.

**Comment by jglassenberg** [comment] 2022-04-29 06:19
I didn't get to touch base with the engineer working on this issue today, and they're out Friday.  But a fix is in development at least. I should have a proper update early next week.

**Comment by Alstria** [comment] 2022-05-04 09:35
@jglassenberg Any news on this?

**Comment by jglassenberg** [comment] 2022-05-06 18:28
Development has continued but I can't share details until we have something more definitive, unfortunately.  Sorry that I still don't have a great update, other than that it is an active ticket for our current sprint.

**Comment by jglassenberg** [comment] 2022-05-17 06:09
Sorry for not posting an update last week. I was waiting to confirm what we can share.  And basically, we have a confirmed solution for this dependency, but the estimate is for a release in June.  

I'll continue to keep you all updated on this, but not weekly. I'll follow up end of month to confirm that the fix is on track.  I hope that's alright with you all.

**Comment by rozeboosje** [comment] 2022-05-17 11:43
Thanks Jeremy. I'm happy to wait as long as you need to get it fully tested. So far we have been able to continue moving forward with the last nuGet package that didn't have this issue, without the rest of our Solution having a conniption. As long as that remains the case there is no mad urgency.

**Comment by jglassenberg** [comment] 2022-05-20 23:46
@rozeboosje That's good to hear.  We should have a fix within the coming weeks, so hopefully your solution can work at least until then.

**Comment by jglassenberg** [comment] 2022-05-28 16:09
End of month update, that the fix is on track.  I can't provide too specific an ETA but am expecting the fix to be released in the month of June.

**Comment by jglassenberg** [comment] 2022-06-10 23:21
Semi-weekly update: still on track for a June fix.

**Comment by jglassenberg** [comment] 2022-06-26 05:40
I'm on vacation at the moment, so I haven't gotten to sync with the engineers working on this fix.  I can acknowledge that a fix is under review and still planned for a release end of month.

**Comment by jglassenberg** [comment] 2022-07-05 22:51
News of the week: we have a release candidate for the SDK with a fix, at https://www.nuget.org/packages/DocuSign.eSign.dll/6.0.0-rc.  This version removes the RestSharp dependency and upgrades Newtonsoft.Json to the latest version.  If any of you can give this a try and let me know how it goes while we continue to test it, much appreciated.

**Comment by ypaulau** [comment] 2022-08-29 19:18
@jglassenberg I've migrated our application to SDK 6.0.0-rc from something even older than an SDK version with RestSharp. And, it goes pretty well. Everything I need is working as I expected. BTW Is there a release date for the next version?

**Comment by jglassenberg** [comment] 2022-09-17 07:46
Sorry for the slow reply @ypaulau. We were held up with our latest release, but there was a release just last week.   This should be resolved with that.

**Closed** 2024-07-12 05:54 UTC
Labels: DCM-7204
