### ISSUE TITLE
GenerateAccessToken returns "unsupported_grant_type" on 6.7.0

### ISSUE THREAD

**Issue by rjpr** [docusign/docusign-esign-csharp-client#422] opened 2023-10-03 23:27 UTC
Calling DocuSignClient.GenerateAccessToken on SDK v6.7.0 returns the following exception:

DocuSign.eSign.Client.ApiException: Error while requesting server, received a non successful HTTP code with response Body: {"error":"invalid_grant","error_description":"unsupported_grant_type"}
   at DocuSign.eSign.Client.DocuSignClient.GenerateAccessToken(String clientId, String clientSecret, String code)

I eventually resolved the issue by downgrading to 6.6.0. After some investigation I suspect this has been caused by the changes to the request body here: https://github.com/docusign/docusign-esign-csharp-client/commit/bbc7e3df590ff5a961fb3efc239405367d3bc380#diff-ba42f5f1289226fd9b2414cf211518bd5cdd7a81e4d5764fe74fb90ee6b2ada7R91

**Comment by ByungjaeChung** [comment] 2023-10-04 05:50
Thanks for submitting the issue. I was able to reproduce the same issue and reported internally.

**Comment by Walouh** [comment] 2023-10-18 15:21
I had the same issue, and overrided the behaviour of DocuSignClient.GenerateAccessToken. It is indeed related to the changes you mentionned (here : https://github.com/docusign/docusign-esign-csharp-client/commit/bbc7e3df590ff5a961fb3efc239405367d3bc380#diff-ba42f5f1289226fd9b2414cf211518bd5cdd7a81e4d5764fe74fb90ee6b2ada7R91)

I only had to change the contentType of the docusignRequest to add "application/x-www-form-urlencoded" in the GenerateAccesToken implementation.

Looks like so : 
![image](https://github.com/docusign/docusign-esign-csharp-client/assets/75216882/e5587c40-f186-4d0f-9e09-f12c025805bd)

May I open a pull request to bring this fix in the code base ?

**Comment by kenharris** [comment] 2023-10-27 18:40
Hi all - the `GenerateAcessToken()` method should be fixed in the latest 6.8.0 version released today.

**Closed** 2024-05-07 06:00 UTC
